
import static java.lang.Math.sqrt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author william
 */
public class Triangle extends javax.swing.JFrame {

    /**
     * Creates new form Triangle
     */
    public Triangle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        k2 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        k1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 135, 0, 0);

        cbtn.setText("calculate");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn);
        cbtn.setBounds(140, 300, 75, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triangle.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 50, 189, 189);
        getContentPane().add(h);
        h.setBounds(196, 120, 60, 30);
        getContentPane().add(g2);
        g2.setBounds(120, 130, 50, 20);
        getContentPane().add(k2);
        k2.setBounds(50, 160, 50, 30);
        getContentPane().add(g1);
        g1.setBounds(189, 200, 40, 20);
        getContentPane().add(k1);
        k1.setBounds(160, 240, 50, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
//        while("".equals(h.getText()) || 
//              "".equals(k1.getText()) || 
//              "".equals(k2.getText()) || 
//              "".equals(g1.getText()) || 
//              "".equals(g2.getText())){
            
            if("".equals(h.getText()) && !"".equals(k1.getText()) && !"".equals(k2.getText())) {
                h.setText(Double.toString(sqrt(convert(k1.getText()) * convert(k1.getText()) + convert(k2.getText()) * convert(k2.getText()))));
            }
            if("".equals(k1.getText()) && !"".equals(h.getText()) && !"".equals(k2.getText())) {
                k1.setText(Double.toString(sqrt(convert(h.getText()) * convert(h.getText()) - convert(k2.getText()) * convert(k2.getText()))));
            }
            if("".equals(k2.getText()) && !"".equals(k1.getText()) && !"".equals(h.getText())) {
                k2.setText(Double.toString(sqrt(convert(h.getText()) * convert(h.getText()) - convert(k1.getText()) * convert(k1.getText()))));
            }
//        }
                
    }//GEN-LAST:event_cbtnActionPerformed
    
    private double convert(String input){
        
        double temp = Double.parseDouble(input);
        return temp;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField k1;
    private javax.swing.JTextField k2;
    // End of variables declaration//GEN-END:variables
}
